
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int mayorq = 14;
  public static final int unaomasveces = 3;
  public static final int llavecerradura = 11;
  public static final int disyuncion = 6;
  public static final int a47 = 29;
  public static final int identificador = 17;
  public static final int especialC = 9;
  public static final int comma = 20;
  public static final int a41 = 28;
  public static final int a40 = 27;
  public static final int guion = 13;
  public static final int puntoycoma = 15;
  public static final int llaveapertura = 10;
  public static final int porcentaje = 16;
  public static final int EOF = 0;
  public static final int a39 = 26;
  public static final int a38 = 25;
  public static final int tildeseparacion = 8;
  public static final int error = 1;
  public static final int a36 = 24;
  public static final int a35 = 23;
  public static final int a34 = 22;
  public static final int entero = 18;
  public static final int ceroomasveces = 5;
  public static final int a33 = 21;
  public static final int a96 = 38;
  public static final int a64 = 32;
  public static final int a95 = 37;
  public static final int a94 = 36;
  public static final int a93 = 35;
  public static final int a61 = 31;
  public static final int a92 = 34;
  public static final int dospuntos = 12;
  public static final int a60 = 30;
  public static final int a91 = 33;
  public static final int concatenacion = 4;
  public static final int conj = 2;
  public static final int ceroounavez = 7;
  public static final int cadena = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "conj",
  "unaomasveces",
  "concatenacion",
  "ceroomasveces",
  "disyuncion",
  "ceroounavez",
  "tildeseparacion",
  "especialC",
  "llaveapertura",
  "llavecerradura",
  "dospuntos",
  "guion",
  "mayorq",
  "puntoycoma",
  "porcentaje",
  "identificador",
  "entero",
  "cadena",
  "comma",
  "a33",
  "a34",
  "a35",
  "a36",
  "a38",
  "a39",
  "a40",
  "a41",
  "a47",
  "a60",
  "a61",
  "a64",
  "a91",
  "a92",
  "a93",
  "a94",
  "a95",
  "a96"
  };
}

